fix: refactored code (more to be done)
Martiyn/coffee-machine pull request #6
Opened 2021-11-16 12:11 UTC by Martiyn

Рефакторирах кода, вече е много по-изчистен, постарал съм се да не оставям повтарящ се код. На този етап ще си оставя прогреса в този пул рикуест и ще гледам за допълнителни коментари, подходи и препоръки.

2021-11-16 13:07 UTC, tdermendjiev commented on bin/index.js
> +      Object.assign(coffee, { milkMl: '0.2ml' })
Това можеш да го изнесеш във функция, на която само да подаваш 0.2 мл.

2021-11-16 13:16 UTC, tdermendjiev commented
Нека усложним задачата, за да научиш малко обектно-ориентирано програмиране (https://www.geeksforgeeks.org/introduction-object-oriented-programming-javascript/) 

Създай следните класове:
1. Мелачка (grinder) - отговаря за смилането на зърната. Инициализира се с фабрични настройки за време на работа и колко едро да смила зърната. Трябва да има функция grind(), която може да приема такива настройки. Ако насторйките не са подадени - смила кафето с фабричните.
2. Резервоар за вода - отговаря за подаване на вода към нагревателя.
3. Нагревател за водата - връща загрятата на определена температура вода.
4. Резервоар за мляко
5. Нагревател за мляко - Можем ли да ползваме същия нагревател? Можем ли да използваме общ parent class за двата? Каква е разликата между двата нагревателя(подсказвам - млякото трябва да е на пяна).
6. Вода
7. Мляко
8. Кафе

2021-11-17 07:26 UTC, martinlazarov requested changes

2021-11-17 07:26 UTC, martinlazarov commented on bin/index.js
> +    case "espresso-medium":
@Martiyn тези switch/case може да бъдат спестени. Ако имаш 10 артикула, ще трябва да изброяваш 10 пъти всяка отделна опция колко мляко да ѝ сложиш. Колко мляко трябва да съдържа трябва да бъде най-горе, в самата дефиниция на вида кафе в Map

2021-11-17 07:26 UTC, martinlazarov commented on bin/index.js
> +      Object.assign(coffee, { coffeeAmt: '10mg' })
Същото като млякото

2021-11-17 07:26 UTC, martinlazarov commented on bin/index.js
> +  ['espresso-small'],
Дефинирай го така 
```
const coffeeOptions = new Map();

coffeeOptions.set('espresso-small', {
  milk: 123,
  milkUnit: Units.ML,
  coffeeAmt: 123,
  coffeeAmtUnit: Units.MG
});
```

2021-11-17 07:26 UTC, martinlazarov commented on bin/index.js
> +      Object.assign(coffee, { coffeeAmt: '9mg' })
Дефинирай Обект `Units` и вътре сложи мерните едници, които използваш. Ако сложиш `9mg` по този начин след това ще ти бъде трудно АКО трябва да калкулираш нещо с тези 9 милиграма. Стойността трябва да е число, а вече каква е единицата се дефинира в друго поле от характеристиките на кафето.

2021-11-17 17:51 UTC, martinlazarov requested changes

2021-11-17 17:51 UTC, martinlazarov commented on bin/index.js
> +let coffeeOptions = new Map([
Използвай const вместо let. Обясни разликите и защо трябва в случая да е const

2021-11-17 17:51 UTC, martinlazarov commented on bin/index.js
> +    { grindTime: 3, grindFineness: 'ground', temperature: 190, milkMl: 4, grainsGr: 3, waterMl: 4 }]
Не виждам units да си използвал.

2021-11-17 17:51 UTC, martinlazarov commented on bin/index.js
>  }
Върни направо отговор вместо да запазваш в temporary variable. Виж линка с реакторинг относно temporary variables.

2021-11-17 17:51 UTC, martinlazarov commented on bin/index.js
> +    return ('${this.time},${this.timeUnit},${this.fineness}')
Защо използваш такива апострофи?

2021-11-18 17:53 UTC, martinlazarov requested changes

2021-11-18 17:53 UTC, martinlazarov commented on bin/index.js
> +  Object.assign(coffee, { milkUnit: value.milkUnit })
Object.assign приема като втори параметър обект. Защо не ползваш само един обект и ги сложиш наведнъж, вместо за всяко пропърти нов assign?

2021-11-18 17:53 UTC, martinlazarov commented on bin/index.js
> +    return ('${this.time},${this.timeUnit},${this.fineness}')
@Martiyn ??

2021-11-19 17:40 UTC, martinlazarov requested changes

2021-11-19 17:40 UTC, martinlazarov commented on bin/index.js
> +  ['no-sugar', 'No Sugar'],
Тук трябва да е 0

2021-11-19 17:40 UTC, martinlazarov commented on bin/index.js
> +  ['no-milk', 'No Milk']
0

2021-11-19 17:40 UTC, martinlazarov commented on bin/index.js
> +    Object.assign(coffee, { sugar: selectedAmount }, { sugarUnit: value.sugarUnit })
Не така - 
```
{
sugar: selectedAmount,
sugarUnit: value.sugarUnit
}
```

2021-11-22 08:39 UTC, tdermendjiev commented on bin/index.js
> +  passToHeater() {
След като методът се казва "passToHeater", очаквам той да подаде нещо към нагревателя(Heater). Той обаче просто връща някакъв стринг. Ако резервоарът предава нещо към нагревателя, то не трябва ли той да има референция към него и наистина да му подаде някакво количество вода с определена температура?

2021-11-22 08:40 UTC, tdermendjiev commented on bin/index.js
> +  passToHeater() {
Същото като по-горе.

2021-11-22 08:40 UTC, tdermendjiev commented on bin/index.js
> +  passToHeater() {
Същото.

2021-11-22 08:42 UTC, tdermendjiev commented on bin/index.js
> +  heatUpLiquid() {
Какво прави нагревателят? Получава количество вода като input и му повишата температурата, т.е.  output е същото (или различно?) количество вода с определена температура. Т.е. input (параметър)  трябва да е иннстанция на класа в Water, която има температура Х, а output (това което функцията връща) да е същата вода, но с по-висока температура.

2021-11-23 17:16 UTC, martinlazarov requested changes

2021-11-23 17:16 UTC, martinlazarov commented on bin/index.js
> +    return this.liquidPassedFrom, this.temperature, this.temperatureUnit
@Martiyn Тази функция какво ще върне? Това е грешен синтаксис за връщане на стойност от функция.

2021-11-23 17:16 UTC, martinlazarov commented on bin/index.js
> +class Water {
Какво прави този клас?

2021-11-23 17:16 UTC, martinlazarov commented on bin/index.js
> +    return this.liquidPassedFrom, this.temperature, this.temperatureUnit
Същия проблем като по-горе.

2021-11-24 11:44 UTC, tdermendjiev commented on bin/index.js
> +  passToHeater() {
Функцията се казва passToHeater, а не виждам да прави това, което пише - според името тя трябва да предава течността към нагревател, а просто връща течността. Т.е. можеше да се казва просто getLiquid().

2021-12-02 13:33 UTC, martinlazarov approved these changes

2021-12-18 10:42 UTC, merged